[versions]
junit = "5.14.0"

[libraries]
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[bundles]
java-testing = [ "junit-api" ]

[plugins]
java-qa = { id = "org.danilopianini.gradle-java-qa", version = "1.87.0"}
